#---- GENERAL
GPU: 0
VERBOSE: False

#---- PATHS
MODEL_DIR: 'bin/'
RESULTS_DIR: 'results/'
LOG_DIR: 'logs/'

#---- DATASET
DATASET: 'openpose_mp'
DATA_TYPE: '2d_body_hands'  # 2d_body, 2d_body_hands
SUBDIR: '1'
SEEDS: [11331, 11435, 12123, 53453, 42344, 24234, 65747, 84443, 29345, 99543]

openpose:
    KEYPOINTS: 13
    CLASSES: 20
    FRAMES: 30
openpose_coco:
    KEYPOINTS: 13
    CLASSES: 33
    FRAMES: 30
openpose_mp:
    KEYPOINTS: 53
    CLASSES: 33
    FRAMES: 30

LABELS_VO: ['NA', 'align leg screw with table thread', 'align side panel holes with front panel dowels',
         'attach drawer back panel', 'attach drawer side panel', 'attach shelf to table', 'flip shelf',
         'flip table', 'flip table top', 'insert drawer pin', 'lay down back panel', 'lay down bottom panel',
         'lay down front panel', 'lay down leg', 'lay down shelf', 'lay down side panel', 'lay down table top',
         'other', 'pick up back panel', 'pick up bottom panel', 'pick up front panel', 'pick up leg', 'pick up pin',
         'pick up shelf', 'pick up side panel', 'pick up table top', 'position the drawer right side up', 'push table',
         'push table top', 'rotate table', 'slide bottom of drawer', 'spin leg', 'tighten leg']

LABELS_V: ['NA', 'align', 'attach', 'flip', 'insert', 'lay down', 'other', 'pick up', 'position', 'push', 'rotate',
           'slide', 'spin', 'tighten']

#---- MODEL
MODEL_SIZE: 'nulla'
micro:        
    N_HEADS: 1
    N_LAYERS: 4
    EMBED_DIM: 64
    DROPOUT: 0.1
    MLP: 256
small:    
    N_HEADS: 2
    N_LAYERS: 5
    EMBED_DIM: 128
    DROPOUT: 0.5
    MLP: 256
base:
    N_HEADS: 3
    N_LAYERS: 6
    EMBED_DIM: 192
    DROPOUT: 0.5
    MLP: 256


#---- TRAINING SETTINGS 
SCHEDULER: True
VELOCITY: True
N_EPOCHS: 250 #350
BATCH_SIZE: 256 #256
WEIGHT_DECAY: 0.000283 #0.0001
WARMUP_PERC: 0.3
STEP_PERC: 0.8 #0.8
LABEL_SMOOTHING: 0.262

#---- RANDOM SEARCH
N_TRIALS: 250 #null

#---- TEST SETTINGS
WEIGHTS: '/home/louis/Data/Fernandez_HAR/AcT_pretrained_weights/openpose/micro/AcT_micro.h5'
